<?php

use Google\Service\Drive;
use Google\Service\Sheets;

$serviceFile = env('GOOGLE_SERVICE_ACCOUNT_JSON_LOCATION', '');
if (! empty($serviceFile)) {
    $isWindowsAbs = preg_match('~^[a-zA-Z]:\\\\~', $serviceFile) === 1;
    $isUnixAbs = str_starts_with($serviceFile, '/');

    if (! $isWindowsAbs && ! $isUnixAbs) {
        $serviceFile = base_path($serviceFile);
    }
}

return [
    /*
    |----------------------------------------------------------------------------
    | Google application name
    |----------------------------------------------------------------------------
    */
    'application_name' => env('GOOGLE_APPLICATION_NAME', ''),

    /*
    |----------------------------------------------------------------------------
    | Google OAuth 2.0 access
    |----------------------------------------------------------------------------
    */
    'client_id' => env('GOOGLE_CLIENT_ID', ''),
    'client_secret' => env('GOOGLE_CLIENT_SECRET', ''),
    'redirect_uri' => env('GOOGLE_REDIRECT', ''),

    /*
    |----------------------------------------------------------------------------
    | Scopes
    |----------------------------------------------------------------------------
    | Required for Service Account auth.
    */
    'scopes' => [
        Sheets::SPREADSHEETS,
        Drive::DRIVE,
    ],

    'access_type' => 'online',
    'prompt' => 'consent select_account',

    /*
    |----------------------------------------------------------------------------
    | Google developer key
    |----------------------------------------------------------------------------
    */
    'developer_key' => env('GOOGLE_DEVELOPER_KEY', ''),

    /*
    |----------------------------------------------------------------------------
    | Google service account
    |----------------------------------------------------------------------------
    */
    'service' => [
        'enable' => env('GOOGLE_SERVICE_ENABLED', false),
        'file' => $serviceFile,
    ],

    /*
    |----------------------------------------------------------------------------
    | Additional config for the Google Client
    |----------------------------------------------------------------------------
    */
    'config' => [],

    /*
    |----------------------------------------------------------------------------
    | App-specific settings for this project
    |----------------------------------------------------------------------------
    */
    'spreadsheet_id' => env('GOOGLE_SPREADSHEET_ID', env('GOOGLE_SHEET_ID', '')),
    'sheet_name' => env('GOOGLE_SHEET_NAME', 'Sheet1'),

    /*
    |----------------------------------------------------------------------------
    | System -> Sheet tab mapping (Google Sheets worksheet titles)
    |----------------------------------------------------------------------------
    | Each selected system will be appended to its corresponding sheet tab.
    | Tabs are auto-created if missing.
    */
    'sheet_by_system' => [
        'ATM Portal' => env('GOOGLE_SHEET_ATM', 'ATM Portal'),
        'SMS Portal' => env('GOOGLE_SHEET_SMS', 'SMS Portal'),
        'MSP-ISS Portal' => env('GOOGLE_SHEET_MSP', 'MSP-ISS Portal'),
        'MSP-ISS FTP' => env('GOOGLE_SHEET_FTP', 'MSP-ISS FTP'),
        'CORE 3.0' => env('GOOGLE_SHEET_CORE', 'CORE 3.0'),
        'MVM Portal' => env('GOOGLE_SHEET_MVM', 'MVM Portal'),
    ],

    // Used for systems that don't have a detailed block/tab mapping (Helpdesk, PASS, etc.)
    'sheet_other' => env('GOOGLE_SHEET_OTHER', 'Other Systems'),

    /*
    |--------------------------------------------------------------------------
    | Request number counter sheet
    |--------------------------------------------------------------------------
    | Request numbers are generated by counting existing "Request Number" values
    | (format: REQ-DAY-XXX) for the current day prefix, then incrementing.
    |
    | Set this to a single, stable sheet tab that always receives submissions
    | (commonly your default sheet), so the counter is consistent.
    */
    'request_number_sheet' => env('GOOGLE_REQUEST_NUMBER_SHEET', env('GOOGLE_SHEET_NAME', 'Sheet1')),

    /*
    |--------------------------------------------------------------------------
    | Sheet row 1 headers used when syncing admin approval/rejection
    |--------------------------------------------------------------------------
    | "Status" is required (already used for new submissions). Optionally add
    | columns using these exact labels, or one of the aliases on the same row.
    */
    'sheet_sync_approval_headers' => [
        'status' => ['Status'],
        'approved_by' => ['Approved By', 'Processed By'],
        'approved_at' => ['Approved At', 'Processed Date'],
        'approval_remarks' => ['Approval Remarks', 'Remarks', 'Admin Remarks'],
    ],
];
